apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # No namespace.yaml — kube-system is created by Talos, and is the one
  # namespace exempt from its PodSecurity enforcement. See helmrelease.yaml.
  - cni-configuration.yaml
  - helmrelease.yaml
