apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastapi-echo
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/lestherll/fastapi-echo
  ref:
    branch: main
