apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-tailscale.yaml
  - helmrepository-prometheus-community.yaml
  - gitrepository-fastapi-echo.yaml
  - gitrepository-personal-finance-dashboard.yaml
  - helmrepository-cloudnative-pg.yaml
  - helmrepository-kro.yaml
