# Encrypted with sops — see .sops.yaml for the age recipient.
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NwSxspc=,iv:OZxNIH7ARULwEbhZewmI2UgbiB2/KAfSb32yXtJbrGk=,tag:QQDVz2CITwxv/9p2UjFogg==,type:str]
    admin-password: ENC[AES256_GCM,data:2//MWCdQo2RPUxhozDBeuzJxNvlmVEJK7a0EJxgafq0=,iv:oLQvxKrDmltz7Bgg0DolrJ5VG5/d/Ohy5kyy8DaIdtI=,tag:eYpzgku5bAG3x3je6bs0ZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERElYRW9aMkVjaTVmK3l3
            bDByNjBxWVYrL093TDl4WENKVG94N3ZFMkg0CjRqS2ptemM0Q1M4V3ZSRW9uRURt
            RWFYWHZlM2ZabkpkemRHb1Q2cG11dmsKLS0tIDFuUG9RVFdKUjcvc3Q2ZVJaMlBG
            ajk0VEhNcERLZzRIcGQzdDNlWlRydUkKeaFNrM58dDvQlxmyPFgr0mqflbjzb2Jw
            3oOiJZDT2lZZgbiUfzU6vbKcH3GXAW8WkgBqKulrh9IkFC3kNwRC4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qr7amd9hzgd5eql673nxqt3pdf4c43pjk42dg7lfd9ern7uzrasqtf6gnc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T09:28:36Z"
    mac: ENC[AES256_GCM,data:UoVJD6BwItsHyPS6A9ekPAqZ7hC+Pc9iPAuxW7B/nMu12Q8gHY4ss3uWspTPtsS8GawpXkpLe3J030hjx6szZf9YQojsate2TJj/YwxYn1VBcssU4kaBTrGBihAlEnf0SwLYWXwlBuqfmiTpH8b2nrpyfSp7tY0kJV6n+a7loFw=,iv:Dmyw64NAVYx+LUaJaUbN9Pd4AVTusKwwJ3lqXbl/JXo=,tag:T/6R7meF2TFoV88PV8WUbg==,type:str]
    version: 3.13.3
